apiVersion: v1
kind: Service
metadata:
  name: "flux-manager"
  labels:
    app: "flux-manager"
{{- with .Values.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: "flux-manager"